# Generated by Django 6.0.2 on 2026-02-20 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('social_name', models.CharField(max_length=255)),
                ('profession', models.CharField(choices=[('Doctor', 'Médico(a)'), ('Nurse', 'Enfermeiro(a)'), ('psychologist', 'Psicólogo(a)'), ('physiotherapist', 'Fisioterapeuta'), ('nutritionist', 'Nutricionista'), ('other', 'Outro')], default='other', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('health_professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='api.healthprofessional')),
            ],
        ),
    ]
